[[constraint]]
  name = "github.com/hellofresh/logging-go"
  version = "v0.3.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "^v1.3.0"

[[constraint]]
  name = "github.com/hellofresh/health-go"
  version = "v2.1.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "^4.0.2"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "^1.0.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "^0.7.10"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "^1.2.0"

[[override]]
  name = "github.com/google/uuid"
  version = "^1.1.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
