FROM golang:1.12

RUN go get github.com/githubnemo/CompileDaemon \
    && go get github.com/golangci/golangci-lint/cmd/golangci-lint \
    && go get golang.org/x/tools/cmd/goimports \
    && go get github.com/go-playground/overalls

WORKDIR /go/src/github.com/dohernandez/geolocation-service

CMD make run-compile-daemon
